stages:
  - build
  - deploy

variables:
  ITCHIO_USERNAME: $ITCH_USER
  ITCHIO_GAME: $ITCH_GAME
  BUTLER_API_KEY: $BUTLER_API_KEY
  GODOT_VERSION: 4.5
  EXPORT_NAME: Project
  PROJECT_PATH: project

before_script:
  - mkdir -v -p ~/.local/share/godot/export_templates
  - mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

build_windows:
  stage: build
  image: barichello/godot-ci:4.5
  script:
    - mkdir -v -p build/windows
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "Windows" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
  artifacts:
    paths:
      - build/windows

build_linux:
  stage: build
  image: barichello/godot-ci:4.5
  script:
    - mkdir -v -p build/linux
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
  artifacts:
    paths:
      - build/linux

build_web:
  stage: build
  image: barichello/godot-ci:4.5
  script:
    - mkdir -v -p build/html5
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "HTML5" "$EXPORT_DIR/html5/index.html"
  artifacts:
    paths:
      - build/html5

deploy_to_itch:
  stage: deploy
  image: barichello/godot-ci:4.5
  script:
    - ls ./build
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:win
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
    - butler push ./build/html5 $ITCHIO_USERNAME/$ITCHIO_GAME:html5
