image: barichello/godot-ci:4.5

cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - export
  - deploy

variables:
  EXPORT_NAME: project
  PROJECT_PATH: project

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  script:
    - godot --headless --verbose --editor --quit

linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "Windows" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

html5:
  stage: export
  script:
    - mkdir -v -p build/html5
    - EXPORT_DIR="$(readlink -f build)"
    - cd $PROJECT_PATH
    - godot --headless --verbose --export-release "HTML5" "$EXPORT_DIR/html5/index.html"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/html5

# Itch.io Deploy
itchio:linux:
  stage: deploy
  script:
    - butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux

itchio:windows:
  stage: deploy
  script:
    - butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows

itchio:html5:
  stage: deploy
  script:
    - butler push ./build/html5 $ITCHIO_USERNAME/$ITCHIO_GAME:html5
  dependencies:
    - html5