name: Godot CI/CD Pipeline
on:
  push:

env:
  ITCHIO_USERNAME: ${{ secrets.ITCH_USER }}
  ITCHIO_GAME: ${{ secrets.ITCH_GAME }}
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  GODOT_VERSION: 4.5
  EXPORT_NAME: Project
  PROJECT_PATH: project

jobs:
  deploy:
    name: Build and deploy to itch.io
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
      - name: Web Build
        run: |
          mkdir -v -p build/html5
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" "$EXPORT_DIR/html5/index.html"
      - name: Itch.io Deploy
        run: |
          ls ./build
          butler push ./build/windows $ITCHIO_USERNAME/$ITCHIO_GAME:win
          butler push ./build/linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
          butler push ./build/html5 $ITCHIO_USERNAME/$ITCHIO_GAME:html5