name: Godot CI/CD Pipeline

on:
  push:

env:
  GODOT_VERSION: 4.5
  GODOT_STATUS: stable
  EXPORT_NAME: project
  PROJECT_PATH: project

jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.5
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - name: Cache import assets
        uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: Import assets
        run: godot --headless --verbose --editor --quit

  linux:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.5
    needs: import-assets
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
      - uses: actions/upload-artifact@v6
        with:
          name: linux
          path: build/linux

  windows:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.5
    needs: import-assets
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
      - uses: actions/upload-artifact@v6
        with:
          name: windows
          path: build/windows

  html5:
    runs-on: ubuntu-latest
    container: barichello/godot-ci:4.5
    needs: import-assets
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: .godot/imported/
          key: import-assets-${{ runner.os }}-${{ github.sha }}
      - name: setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: build
        run: |
          mkdir -v -p build/html5
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "HTML5" "$EXPORT_DIR/html5/index.html"
      - uses: actions/upload-artifact@v6
        with:
          name: html5
          path: build/html5

  deploy-to-itchio-linux:
    runs-on: ubuntu-latest
    needs: [linux, windows, html5]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: linux
      - name: Deploy to Itch.io (Windows)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: linux.zip

  deploy-to-itchio-windows:
    runs-on: ubuntu-latest
    needs: [linux, windows, html5]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: windows
      - name: Deploy to Itch.io (Windows)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: windows.zip

  deploy-to-itchio-web:
    runs-on: ubuntu-latest
    needs: [linux, windows, html5]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: html5
      - name: Deploy to Itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: html5.zip